# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: '#about'
    weight: 10
  - name: Courses
    url: courses/
    weight: 30
  - name: Experience
    url: '#experience'
    weight: 40
  # - name: Posts
  #   url: '#posts'
  #   weight: 40
  - name: Photos
    url: https://djshives.myportfolio.com/home
    weight: 50
  # - name: Talks
  #   url: '#talks'
  #   weight: 60
  # - name: Publications
  #   url: '#featured'
  #   weight: 70
  - name: Contact
    url: '#contact'
    weight: 60
